apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-table
spec:
  forProvider:
    privileges:
      - DROP
      - INSERT
      - SELECT
    table: test_table
    userRef:
      name: my-user
    databaseRef:
      name: grafana