apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: example-grant-table
spec:
  forProvider:
    privileges:
      - INSERT
      - SELECT
    table: "*"
    userRef:
      name: my-user
    databaseRef:
      name: grafana
---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: Grant
metadata:
  name: test-grant-table
spec:
  forProvider:
    privileges:
      - INSERT
      - SELECT
    table: "*"
    userRef:
      name: test
    databaseRef:
      name: grafana