---
apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: MySQLConnectionSecret
    connectionSecretRef:
      namespace: crossplane-system
      name: crossplane-secret
  # tls one of preferred(default), skip-verify, or true
  tls: preferred