apiVersion: mysql.sql.crossplane.io/v1alpha1
kind: User
metadata:
  name: test
spec:
  forProvider:
    passwordSecretRef:
      name: test
      namespace: crossplane-system
      key: test1234
    resourceOptions:
      maxQueriesPerHour: 1000
      maxUpdatesPerHour: 1000
      maxConnectionsPerHour: 100
      maxUserConnections: 10
  writeConnectionSecretToRef:
    name: test-connection-secret
    namespace: crossplane-system